name: Deploy to CORE SERVER

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: b1.coreserver.jp
          port: 22
          username: knhome
          password: ${{ secrets.FTP_PASSWORD }}
          remote_path: /virtual/knhome/public_html/knhome.jp/fudosan-sell/
          local_path: ./*
          sftp_only: true
