name: Deploy to CORE SERVER

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: b1.coreserver.jp
          username: knhome
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/knhome.jp/fudosan-sell/
          local-dir: ./
